pull

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,19 +1,15 @@
 # CircleCI 2.1 configuration file
 version: 2.1
-workflows:
-  React:
-    jobs:
-      - build
 
-jobs:
-  build:
+executors:
+  node-executor:
     docker:
       - image: circleci/node:12.6
         environment:
           TERM: xterm # this enables colors in the Cypress output
 
-    working_directory: ~/project
-
+commands:
+  netlify-build:
     steps:
       # Clone repo
       - checkout
@@ -40,6 +36,9 @@ jobs:
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
             chmod +x cc-test-reporter
             sudo mv cc-test-reporter /usr/local/bin/cc-test-reporter
+
+            # install netlify-cli
+            sudo npm install netlify-cli -g
 
       # Restore dependencies from cache
       - restore_cache:
@@ -68,13 +67,17 @@ jobs:
           command: |
             set +e
             error=0
+            error_msgs=()
 
             # Add node programs to path
             export PATH=$PATH:node_modules/.bin
 
             # Run unit tests
             npm run test-unit-coverage
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Unit tests failed")
+            fi
 
             # Run integration tests
             cp package.json package.json.default
@@ -82,48 +85,84 @@ jobs:
             npm start &
             wait-on http://localhost:3000
             npm run test-integration-run
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Integration tests failed")
+            fi
             npm stop
             mv package.json.default package.json
 
             npm run test-integration-results-report
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Generation of integration test report failed")
+            fi
             rm -rf test-results/integration-tests/specs
 
             npm run test-integration-coverage-report
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Generation of integration test coverage report failed")
+            fi
 
             # check for missing and unused dependencies
             depcheck .
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Test for missing and unused dependencies failed")
+            fi
 
             # Lint JavaScript
             npm run lint-js
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("JavaScript linting failed")
+            fi
 
             # Lint CSS
             npm run lint-style
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("CSS linting failed")
+            fi
 
             # Lint JSON
             npm run lint-json
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("JSON linting failed")
+            fi
 
-            # Lint svg
+            # Lint SVG
             npm run lint-svg
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("SVG linting failed")
+            fi
 
             # Build production package
             NODE_ENV=production npm run build
-            if [[ $? -ne 0 ]]; then error=1; fi
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Production build failed")
+            fi
 
             # Generate report of licenses of dependencies
             npm run build-third-party-license-report
+            if [[ $? -ne 0 ]]; then
+              error=1;
+              error_msgs+=("Generation of license report failed")
+            fi
 
             # Return error status
             if [[ $error -eq 0 ]]; then
               exit 0;
             else
+              NEWLINE=$'\n'
+              error_msg=$(printf "${NEWLINE}- %s" "${error_msgs[@]}")
+              error_msg=${error_msg:1}
+              >&2 echo "Build failed:"
+              >&2 echo "${error_msg}"
               exit 1;
             fi
 
@@ -162,3 +201,44 @@ jobs:
       - store_artifacts:
           path: ~/project/LICENSE-THIRD-PARTY
           destination: LICENSE-THIRD-PARTY
+
+workflows:
+  version: 2
+  build-deploy:
+    jobs:
+      - build: # anything that's not master branch
+          filters:
+            branches:
+              ignore:
+                - master
+      - release: # only master branch
+          filters:
+            branches:
+              only:
+                - master
+
+jobs:
+  build:
+    executor: node-executor
+    working_directory: ~/project
+    steps:
+      - netlify-build
+      - run:
+          name: Netlify Deploy Non-master Branch
+          command: |
+            export PATH=$PATH:node_modules/.bin
+
+            # deploy
+            netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=build
+  release:
+    executor: node-executor
+    working_directory: ~/project
+    steps:
+      - netlify-build
+      - run:
+          name: Netlify Deploy Master
+          command: |
+            export PATH=$PATH:node_modules/.bin
+
+            # deploy
+            netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
